name: VirtualShop
main: com.SwearWord.VirtualShop.VirtualShop
version: 1.0
commands:
   vs:
      description: Access VirtualShop.
      usage: | 
         /vs buy <amount> item
         /vs sell <amount> <item> <price>
         /vs sell <amount> hand <price>
         /vs remove <item>
         /vs price <item>
         /vs list
         /vs list <page>
         /vs list me
         /vs list <player>
         /vs exchange
         /vs log
         /vs log <player>
   shop:
      description: Access VirtualShop.
      usage: | 
         /shop buy <amount> item
         /shop sell <amount> <item> <price>
         /shop sell <amount> hand <price>
         /shop remove <item>
         /shop price <item>
         /shop list
         /shop list <page>
         /shop list me
         /shop list <player>
         /shop exchange
         /shop log
         /shop log <player>