name: VirtualShop
main: com.SwearWord.VirtualShop.VirtualShop
version: 2.0
commands:
   vs:
      description: Access VirtualShop.
      usage: | 
         /vs buy <amount> item
         /vs sell <amount> <item> <price>
         /vs sell <amount> hand <price>
         /vs remove <item>
         /vs price <item>
         /vs list
         /vs list <page>
         /vs list me
         /vs list <player>
         /vs exchange
         /vs invest <amount>
         /vs rates
         /vs log
         /vs log <player>